version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=linkshortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Qwerty123
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    networks:
      - default
  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    depends_on:
      - postgres
    networks:
      - default
    command: sh -c "/wait && /app/main"
    environment:
       - WAIT_HOSTS=postgres:5432
       - WAIT_HOSTS_TIMEOUT=300
       - WAIT_SLEEP_INTERVAL=30
       - WAIT_HOST_CONNECT_TIMEOUT=30