// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: linkShortener.proto

package proto_linkShortener

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OriginalLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalLink string `protobuf:"bytes,1,opt,name=originalLink,proto3" json:"originalLink,omitempty"`
}

func (x *OriginalLink) Reset() {
	*x = OriginalLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkShortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OriginalLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalLink) ProtoMessage() {}

func (x *OriginalLink) ProtoReflect() protoreflect.Message {
	mi := &file_linkShortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalLink.ProtoReflect.Descriptor instead.
func (*OriginalLink) Descriptor() ([]byte, []int) {
	return file_linkShortener_proto_rawDescGZIP(), []int{0}
}

func (x *OriginalLink) GetOriginalLink() string {
	if x != nil {
		return x.OriginalLink
	}
	return ""
}

type ShortenLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortenLink string `protobuf:"bytes,1,opt,name=shortenLink,proto3" json:"shortenLink,omitempty"`
}

func (x *ShortenLink) Reset() {
	*x = ShortenLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkShortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenLink) ProtoMessage() {}

func (x *ShortenLink) ProtoReflect() protoreflect.Message {
	mi := &file_linkShortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenLink.ProtoReflect.Descriptor instead.
func (*ShortenLink) Descriptor() ([]byte, []int) {
	return file_linkShortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenLink) GetShortenLink() string {
	if x != nil {
		return x.ShortenLink
	}
	return ""
}

var File_linkShortener_proto protoreflect.FileDescriptor

var file_linkShortener_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x6e,
	0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x0c, 0x4f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x2f,
	0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x20, 0x0a,
	0x0b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x32,
	0xae, 0x01, 0x0a, 0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x12, 0x4f, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x1a, 0x20,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4c, 0x69, 0x6e, 0x6b,
	0x22, 0x00, 0x12, 0x4c, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x1a, 0x21, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x00,
	0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x6e,
	0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_linkShortener_proto_rawDescOnce sync.Once
	file_linkShortener_proto_rawDescData = file_linkShortener_proto_rawDesc
)

func file_linkShortener_proto_rawDescGZIP() []byte {
	file_linkShortener_proto_rawDescOnce.Do(func() {
		file_linkShortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_linkShortener_proto_rawDescData)
	})
	return file_linkShortener_proto_rawDescData
}

var file_linkShortener_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_linkShortener_proto_goTypes = []interface{}{
	(*OriginalLink)(nil), // 0: proto_linkShortener.OriginalLink
	(*ShortenLink)(nil),  // 1: proto_linkShortener.ShortenLink
}
var file_linkShortener_proto_depIdxs = []int32{
	0, // 0: proto_linkShortener.linkShortener.Create:input_type -> proto_linkShortener.OriginalLink
	1, // 1: proto_linkShortener.linkShortener.Get:input_type -> proto_linkShortener.ShortenLink
	1, // 2: proto_linkShortener.linkShortener.Create:output_type -> proto_linkShortener.ShortenLink
	0, // 3: proto_linkShortener.linkShortener.Get:output_type -> proto_linkShortener.OriginalLink
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_linkShortener_proto_init() }
func file_linkShortener_proto_init() {
	if File_linkShortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_linkShortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OriginalLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkShortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linkShortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_linkShortener_proto_goTypes,
		DependencyIndexes: file_linkShortener_proto_depIdxs,
		MessageInfos:      file_linkShortener_proto_msgTypes,
	}.Build()
	File_linkShortener_proto = out.File
	file_linkShortener_proto_rawDesc = nil
	file_linkShortener_proto_goTypes = nil
	file_linkShortener_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LinkShortenerClient is the client API for LinkShortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LinkShortenerClient interface {
	Create(ctx context.Context, in *OriginalLink, opts ...grpc.CallOption) (*ShortenLink, error)
	Get(ctx context.Context, in *ShortenLink, opts ...grpc.CallOption) (*OriginalLink, error)
}

type linkShortenerClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkShortenerClient(cc grpc.ClientConnInterface) LinkShortenerClient {
	return &linkShortenerClient{cc}
}

func (c *linkShortenerClient) Create(ctx context.Context, in *OriginalLink, opts ...grpc.CallOption) (*ShortenLink, error) {
	out := new(ShortenLink)
	err := c.cc.Invoke(ctx, "/proto_linkShortener.linkShortener/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkShortenerClient) Get(ctx context.Context, in *ShortenLink, opts ...grpc.CallOption) (*OriginalLink, error) {
	out := new(OriginalLink)
	err := c.cc.Invoke(ctx, "/proto_linkShortener.linkShortener/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkShortenerServer is the server API for LinkShortener service.
type LinkShortenerServer interface {
	Create(context.Context, *OriginalLink) (*ShortenLink, error)
	Get(context.Context, *ShortenLink) (*OriginalLink, error)
}

// UnimplementedLinkShortenerServer can be embedded to have forward compatible implementations.
type UnimplementedLinkShortenerServer struct {
}

func (*UnimplementedLinkShortenerServer) Create(context.Context, *OriginalLink) (*ShortenLink, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedLinkShortenerServer) Get(context.Context, *ShortenLink) (*OriginalLink, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterLinkShortenerServer(s *grpc.Server, srv LinkShortenerServer) {
	s.RegisterService(&_LinkShortener_serviceDesc, srv)
}

func _LinkShortener_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginalLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_linkShortener.linkShortener/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServer).Create(ctx, req.(*OriginalLink))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkShortener_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_linkShortener.linkShortener/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServer).Get(ctx, req.(*ShortenLink))
	}
	return interceptor(ctx, in, info, handler)
}

var _LinkShortener_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_linkShortener.linkShortener",
	HandlerType: (*LinkShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _LinkShortener_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _LinkShortener_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "linkShortener.proto",
}
